// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Listing struct {
	ID             int      `json:"id"`
	Company        string   `json:"company"`
	Title          string   `json:"title"`
	JobType        string   `json:"jobType"`
	JobDescription string   `json:"jobDescription"`
	Category       *string  `json:"category"`
	StreetAddress  *string  `json:"streetAddress"`
	City           *string  `json:"city"`
	Country        *string  `json:"country"`
	BeginDate      *string  `json:"beginDate"`
	Compentation   *float64 `json:"compentation"`
}

type ListingInput struct {
	ID             *int     `json:"id"`
	Company        string   `json:"company"`
	Title          string   `json:"title"`
	JobType        string   `json:"jobType"`
	JobDescription string   `json:"jobDescription"`
	Category       *string  `json:"category"`
	StreetAddress  *string  `json:"streetAddress"`
	City           *string  `json:"city"`
	Country        *string  `json:"country"`
	BeginDate      *string  `json:"beginDate"`
	Compentation   *float64 `json:"compentation"`
}
